spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sduran19/NearWorkConfigData
  security:
    user:
      name: admin
      password: admin
server:
  port: 9000